all:
  hosts:
    node1:
      ansible_host: 192.168.1.55
      ip: 192.168.1.55
    node2:
      ansible_host: 192.168.1.56
      ip: 192.168.1.56
    node3:
      ansible_host: 192.168.1.57
      ip: 192.168.1.57

  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

