all:
  hosts:
    node1:
      ansible_host: 192.168.1.200
      ip: 192.168.1.200
    node2:
      ansible_host: 192.168.1.210
      ip: 192.168.1.210
    node3:
      ansible_host: 192.168.1.220
      ip: 192.168.1.220

  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

